/**
 * VOS3000 挂断原因码映射表
 *
 * 来源：VOS3000 话单推送 disconnect_cause 字段（p[48]）
 * 包含 VOS 内部错误码 + SIP 标准响应码
 */

const DISCONNECT_CODES = {
  // ===== VOS 内部错误码（负数） =====
  '-101': '隔离策略受限',
  '-100': '被叫超时',
  '-99': '无 SIP 域',
  '-98': '无响应',
  '-97': '无媒体资源',
  '-96': '号码恢复失败',
  '-95': '媒体地理受限',
  '-94': 'SDP 地理受限',
  '-93': '外部黑名单',
  '-92': '终端黑名单',
  '-91': '主叫呼叫转移',
  '-90': '呼叫时段受限',
  '-89': '信令地理受限',
  '-88': '采集异常',
  '-87': '采集转换失败',
  '-86': '采集时长过短',
  '-85': '虚拟号码过期',
  '-84': '虚拟号码循环',
  '-83': '本地 IP 受限',
  '-82': '拉起受限',
  '-81': '回拨第二路受限',
  '-80': '媒体转发失败',
  '-79': 'LRN 失败',
  '-78': 'LRN 号码受限',
  '-77': '分钟费率受限',
  '-76': '速率受限',
  '-75': '系统只读',
  '-74': '语音端口不足',
  '-73': 'SMAP 预留失败',
  '-72': 'SMAP 预留超时',
  '-71': '呼叫保持失败',
  '-70': '号码受限',
  '-69': '无可用路由',
  '-68': '主叫线路预留',
  '-67': '国内业务受限',
  '-66': '结算账户锁定',
  '-65': '结算账户过期',
  '-64': '结算账户注销',
  '-63': '结算账户余额不足',
  '-62': '落地网关无结算账户',
  '-61': '落地网关异常',
  '-60': '通话时长受限',
  '-59': '无接入号呼叫权限',
  '-58': '无接入号费率',
  '-57': '呼叫重定向',
  '-56': '账户已欠费',
  '-55': '无语音数据超时',
  '-54': '被叫话机无账户',
  '-53': '被叫账户余额不足',
  '-52': '被叫账户过期',
  '-51': '被叫账户注销',
  '-50': '被叫账户锁定',
  '-49': '被叫号码受限',
  '-48': '主叫号码受限',
  '-47': '被叫呼叫转移',
  '-46': '第三方账户不可用',
  '-45': '语音编码不匹配',
  '-44': '汇率不存在',
  '-43': '被叫无应答',
  '-42': '协议限制',
  '-41': '连接超时',
  '-40': '未知原因 40',
  '-39': '被叫忙',
  '-38': '账户锁定',
  '-37': '会话超时',
  '-36': '主叫号码受限',
  '-35': '号码长度受限',
  '-34': '处理超时',
  '-33': '被叫号码错误',
  '-32': '主叫前缀受限',
  '-31': '未注册',
  '-30': '被叫锁定',
  '-29': '被叫前缀受限',
  '-28': '主叫锁定',
  '-27': '通话建立超时',
  '-26': '账户过期',
  '-25': '超出线数',
  '-24': '超出授权线数',
  '-23': '强制挂断',
  '-22': '账户已注销',
  '-21': '被叫不在线',
  '-20': '被叫话机忙',
  '-19': '被叫不在线前转',
  '-18': '前转号码不存在',
  '-17': '时段前转',
  '-16': '遇忙前转',
  '-15': '被叫无应答前转',
  '-14': '被叫前转环路',
  '-13': '被叫前转',
  '-12': '被叫免打扰',
  '-11': '被叫关闭连接',
  '-10': '主叫关闭连接',
  '-9': '非法呼叫',
  '-8': '被叫挂断',
  '-7': '主叫挂断',
  '-6': '呼叫鉴权失败',
  '-5': '费率不存在',
  '-4': '无振铃异常挂断',
  '-3': '账户不存在',
  '-2': '账户余额不足',
  '-1': '无此呼叫权限',

  // ===== 0 =====
  '0': '操作成功',

  // ===== ISUP / Q.850 cause codes (1-127) =====
  '1': 'UnallocatedNumber',
  '2': 'NoRouteToNetwork',
  '3': 'NoRouteToDestination',
  '4': 'SendSpecialTone',
  '5': 'MisdialledTrunkPrefix',
  '6': 'ChannelUnacceptable',
  '7': 'CallAwarded',
  '8': 'Preemption',
  '9': 'PreemptionCircuitReserved',
  '16': 'NormalCallClearing',
  '17': 'UserBusy',
  '18': 'NoResponse',
  '19': 'NoAnswer',
  '20': 'SubscriberAbsent',
  '21': 'CallRejected',
  '22': 'NumberChanged',
  '23': 'Redirection',
  '25': 'ExchangeRoutingError',
  '26': 'NonSelectedUserClearing',
  '27': 'DestinationOutOfOrder',
  '28': 'InvalidNumberFormat',
  '29': 'FacilityRejected',
  '30': 'StatusEnquiryResponse',
  '31': 'NormalUnspecified',
  '34': 'NoCircuitChannelAvailable',
  '35': 'CallQueued',
  '38': 'NetworkOutOfOrder',
  '39': 'FrameModeOOS',
  '40': 'FrameModeOperational',
  '41': 'TemporaryFailure',
  '42': 'Congestion',
  '43': 'AccessInformationDiscarded',
  '44': 'RequestedCircuitNotAvailable',
  '46': 'PrecedenceCallBlocked',
  '47': 'ResourceUnavailable',
  '49': 'QoSNotAvailable',
  '50': 'RequestedFacilityNotSubscribed',
  '52': 'OutgoingCallsBarred',
  '53': 'OutgoingCallsBarredInCUG',
  '54': 'IncomingCallsBarred',
  '55': 'IncomingCallsBarredInCUG',
  '57': 'BearerCapNotAuthorised',
  '58': 'BearerCapNotPresentlyAvailable',
  '62': 'InconsistentOutgoingIE',
  '63': 'ServiceOptionNotAvailable',
  '65': 'BearerCapNotImplemented',
  '66': 'ChannelTypeNotImplemented',
  '69': 'RequestedFacilityNotImplemented',
  '70': 'OnlyRestrictedDigitalBearerCapAvailable',
  '79': 'ServiceOrOptionNotImplemented',
  '81': 'InvalidCallReference',
  '82': 'IdentifiedChannelNonExistent',
  '83': 'CallIdentifyNotSuspendedCall',
  '84': 'CallIdentifyInUse',
  '85': 'NoCallSuspended',
  '86': 'ClearedRequestedCallIdentity',
  '87': 'UserNotInCUG',
  '88': 'IncompatibleDestination',
  '90': 'NonexistentCUG',
  '91': 'InvalidTransitNetwork',
  '95': 'InvalidMessageUnspecified',
  '96': 'MandatoryIEMissing',
  '97': 'MessageTypeNonexistent',
  '98': 'MessageNotCompatible',
  '99': 'IENonExistantOrNotImplemented',
  '100': 'InvalidIEContents',
  '101': 'MessageNotCompatibleWithCallState',
  '102': 'TimerExpiry',
  '103': 'ParameterNonexistent',
  '110': 'UnrecognisedParamaterDiscarded',
  '111': 'ProtocolErrorUnspecified',
  '127': 'InterworkingUnspecified',
  '128': 'ErrorInCauseIE',

  // ===== SIP 响应码 (3xx-6xx) =====
  '300': 'Multiple Choices',
  '301': 'Moved Permanently',
  '302': 'Moved Temporarily',
  '305': 'Use Proxy',
  '380': 'Alternative Service',
  '400': 'Bad Request',
  '401': 'Unauthorized',
  '402': 'Payment Required',
  '403': 'Forbidden',
  '404': 'Not Found',
  '405': 'Method not Allowed',
  '406': 'Not Acceptable',
  '407': 'Proxy authentication Required',
  '408': 'Request Timeout',
  '410': 'Gone',
  '413': 'Request Entity Too Large',
  '414': 'Request-URI Too Long',
  '415': 'Unsupported Media Type',
  '416': 'Unsupported URI Scheme',
  '417': 'Bad Extension',
  '421': 'Extension Required',
  '422': 'Session Interval Too Small',
  '423': 'Interval Too Brief',
  '472': 'ALI ERROR 472',
  '473': 'ALI ERROR 473',
  '475': 'ALI ERROR 475',
  '480': 'Temporarily Unavailable',
  '481': 'Call/Transaction Does not Exist',
  '482': 'Loop Detected',
  '483': 'Too Many Hops',
  '484': 'Address Incomplete',
  '485': 'Ambiguous',
  '486': 'Busy Here',
  '487': 'Request Terminated',
  '488': 'Not Acceptable Here',
  '491': 'Request Pending',
  '500': 'Server Internal Error',
  '501': 'Not Implemented',
  '502': 'Bad Gateway',
  '503': 'Service Unavailable',
  '504': 'Server Time-out',
  '505': 'Version not Supported',
  '513': 'Message Too Large',
  '600': 'Busy Everywhere',
  '603': 'Decline',
  '604': 'Does not Exist Anywhere',
  '606': 'Not Acceptable',
}

/**
 * 获取挂断原因的中文描述
 * @param {string|number} code - 挂断原因码
 * @returns {string} 中文描述，未匹配则返回原始码
 */
export function getDisconnectText(code) {
  if (code === '' || code === null || code === undefined) return '-'
  const key = String(code).trim()
  return DISCONNECT_CODES[key] || key
}

/**
 * 获取挂断原因的类型（用于颜色标签）
 * 规则：通话接通后正常挂断 = 绿色"成功"，其他 = 红色"失败"
 * 成功码：-7(主叫挂断)/-8(被叫挂断)/-10(主叫关闭连接)/-11(被叫关闭连接)/0(操作成功)/16(正常清除)
 * @param {string|number} code - 挂断原因码
 * @returns {string} 'success' | 'fail'
 */
export function getDisconnectType(code) {
  if (code === '' || code === null || code === undefined) return 'fail'
  const num = parseInt(code)
  if (isNaN(num)) return 'fail'
  // 接通后正常挂断都算成功
  if (num === -7 || num === -8 || num === -10 || num === -11 || num === 0 || num === 16) return 'success'
  return 'fail'
}

/**
 * 获取所有挂断原因码选项（用于下拉筛选）
 * 格式: code_text，如 "-7_主叫挂断"
 * @returns {Array<{code:string, label:string}>}
 */
export function getDisconnectOptions() {
  return Object.entries(DISCONNECT_CODES).map(([code, text]) => ({
    code,
    label: `${code}_${text}`,
  }))
}
